[project]
name = "mcp-client"
version = "0.1.0"
description = "A simple MCP client"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.40.0",
    "mcp>=1.1.1",
    "python-dotenv>=1.0.1",
]
